source 'https://rubygems.org'

gem 'rails', github: "rails/rails"
gem 'sprockets-rails', github: "rails/sprockets-rails"
gem 'sprockets', github: "rails/sprockets"
gem 'sass-rails', github: "rails/sass-rails"
gem 'arel', github: "rails/arel"
gem 'rack', github: "rack/rack"
gem 'uglifier', '>= 1.3.0'
gem 'her'
gem 'slim-rails'
gem 'coffee-rails'

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', github: 'rails/web-console'
  gem 'spring'
  gem 'listen', '~> 3.0.5'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
