# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8839fbb1b88f9bbfc23c0b8a2c53deaa904979c9b795af24bedf9b902c6489456894dd24ee577f1082ba109ed7b44c21da99f3891f13e05ef1183600ba84ef8

test:
  secret_key_base: 76ff23de65b1c275acc3bfd1129a3989ef21ec0b5c216bf9af06d37d639df9aed7fba972b6a94a9ca730c5eb3c2e4858fa3494737e1a6cace62505070dd02699

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
